### ISSUE TITLE
possibly model.train() forgotten

### ISSUE THREAD

**Issue by programehr** [ModelOrth/MOTH#1]
Hi,
[Here](https://github.com/Gwinhen/MOTH/blob/5133fb2069cf85bc1dc7085508f25d287bc4960b/src_torch/main.py#L416), the model is supposed to be trained. 

Even though `model.train()` is called on [line 79](https://github.com/Gwinhen/MOTH/blob/5133fb2069cf85bc1dc7085508f25d287bc4960b/src_torch/main.py#L79), later when `trigger.generate()` and `TriggerCombo.generate()` are called, they in turn call `model.eval()`, but `model.train()` in not called again before optimization step.

I think it might be an issue, as it raises an error.

**Comment by Gwinhen** [comment]
This should be fine since the trigger generation class makes a copy of the model. I can run the code successfully.

If you encounter the problem, you can add `model.train()` at the end of the trigger generation class.

**Comment by programehr** [comment]
It seems like you were right. The problem was that I had changed the code so that it turned off requires_grad for model params, not with model.eval().
